package ru.aptechka.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light theme ───────────────────────────────────────────────────────────────
val md_light_primary              = Color(0xFF4A7C59)
val md_light_onPrimary            = Color(0xFFFFFFFF)
val md_light_primaryContainer     = Color(0xFFCFE9D5)
val md_light_onPrimaryContainer   = Color(0xFF0B3D1A)
val md_light_secondary            = Color(0xFF836A47)
val md_light_onSecondary          = Color(0xFFFFFFFF)
val md_light_secondaryContainer   = Color(0xFFEFE2CB)
val md_light_onSecondaryContainer = Color(0xFF2A1E08)
val md_light_tertiary             = Color(0xFF4E6868)
val md_light_onTertiary           = Color(0xFFFFFFFF)
val md_light_tertiaryContainer    = Color(0xFFD1E5E5)
val md_light_onTertiaryContainer  = Color(0xFF0C2222)
val md_light_background           = Color(0xFFFAF8F5)
val md_light_onBackground         = Color(0xFF1A1C1A)
val md_light_surface              = Color(0xFFFAF8F5)
val md_light_onSurface            = Color(0xFF1A1C1A)
val md_light_surfaceVariant       = Color(0xFFE0DACE)
val md_light_onSurfaceVariant     = Color(0xFF4C4A44)
val md_light_surfaceContainerLow  = Color(0xFFF5F0E8)
val md_light_surfaceContainer     = Color(0xFFEFE9DF)
val md_light_surfaceContainerHigh = Color(0xFFE9E2D5)
val md_light_outline              = Color(0xFF7A7770)
val md_light_outlineVariant       = Color(0xFFCBC4B8)
val md_light_error                = Color(0xFFC4452D)
val md_light_onError              = Color(0xFFFFFFFF)
val md_light_errorContainer       = Color(0xFFF8DAD2)
val md_light_onErrorContainer     = Color(0xFF3A0008)

// ── Dark theme ────────────────────────────────────────────────────────────────
val md_dark_primary              = Color(0xFFA8D5B4)
val md_dark_onPrimary            = Color(0xFF0E2E18)
val md_dark_primaryContainer     = Color(0xFF2F5240)
val md_dark_onPrimaryContainer   = Color(0xFFC9EFD3)
val md_dark_secondary            = Color(0xFFDCC5A2)
val md_dark_onSecondary          = Color(0xFF3D2C12)
val md_dark_secondaryContainer   = Color(0xFF4A3A22)
val md_dark_onSecondaryContainer = Color(0xFFF4E2C2)
val md_dark_tertiary             = Color(0xFF97CCCC)
val md_dark_onTertiary           = Color(0xFF1B3939)
val md_dark_tertiaryContainer    = Color(0xFF324F4F)
val md_dark_onTertiaryContainer  = Color(0xFFCCE9E9)
val md_dark_background           = Color(0xFF15171A)
val md_dark_onBackground         = Color(0xFFE8E6E2)
val md_dark_surface              = Color(0xFF15171A)
val md_dark_onSurface            = Color(0xFFE8E6E2)
val md_dark_surfaceVariant       = Color(0xFF3D3F3B)
val md_dark_onSurfaceVariant     = Color(0xFFBDB9B0)
val md_dark_surfaceContainerLow  = Color(0xFF1B1E1F)
val md_dark_surfaceContainer     = Color(0xFF22262A)
val md_dark_surfaceContainerHigh = Color(0xFF2A2E33)
val md_dark_outline              = Color(0xFF8E8C85)
val md_dark_outlineVariant       = Color(0xFF3D3F3B)
val md_dark_error                = Color(0xFFF0786A)
val md_dark_onError              = Color(0xFF3A0808)
val md_dark_errorContainer       = Color(0xFF4A1F18)
val md_dark_onErrorContainer     = Color(0xFFFFDAD6)
